// Fleet taxonomy — the states and department categories a fleet vehicle can
// belong to, shared by fleet-compose.html (the pickers + conditional spec
// sections) and wire.html's Fleet tab (filters + labels).
//
// `cat` drives the conditional compose sections:
//   fire      -> water tank / foam tank / CAFS / BA sets
//   ambulance -> stretchers
// Forestry Corporation NSW and NPWS count as fire — they run firefighting
// fleets. The backend stores agency + category as plain strings; this file
// is the single place the lists live.
(function () {
  "use strict";

  const departments = {
    NSW: [
      { name: "NSW Police Force", cat: "police" },
      { name: "Fire and Rescue NSW (FRNSW)", cat: "fire" },
      { name: "NSW Rural Fire Service (RFS)", cat: "fire" },
      { name: "NSW State Emergency Service (SES)", cat: "ses" },
      { name: "NSW Ambulance", cat: "ambulance" },
      { name: "Marine Rescue NSW", cat: "marine" },
      { name: "VRA Rescue NSW", cat: "rescue" },
      { name: "Forestry Corporation NSW", cat: "fire" },
      { name: "National Parks and Wildlife Service", cat: "fire" },
      { name: "Water NSW", cat: "other" },
      { name: "Transport for NSW - Roads", cat: "other" },
      { name: "Transport for NSW - Rail", cat: "other" },
      { name: "Sydney Trains", cat: "other" },
      { name: "Australian Rail Track Corporation", cat: "other" },
    ],
    VIC: [
      { name: "Victoria Police", cat: "police" },
      { name: "Fire Rescue Victoria", cat: "fire" },
      { name: "Country Fire Authority", cat: "fire" },
      { name: "Victoria State Emergency Service", cat: "ses" },
      { name: "Ambulance Victoria", cat: "ambulance" },
    ],
    QLD: [
      { name: "Queensland Police Service", cat: "police" },
      { name: "Queensland Fire Department", cat: "fire" },
      { name: "Rural Fire Service Queensland", cat: "fire" },
      { name: "Queensland SES", cat: "ses" },
      { name: "Queensland Ambulance Service", cat: "ambulance" },
      { name: "Queensland Rail", cat: "other" },
      { name: "Translink", cat: "other" },
    ],
    WA: [
      { name: "WA Police Force", cat: "police" },
      { name: "Department of Fire and Emergency Services (DFES)", cat: "fire" },
      { name: "St John Ambulance WA", cat: "ambulance" },
      { name: "Volunteer Marine Rescue WA", cat: "marine" },
    ],
    SA: [
      // MFS, CFS, SASES (and SAAS alongside) sit under the SA Fire and
      // Emergency Services Commission (SAFECOM); listed individually since a
      // vehicle belongs to a service, not the commission.
      { name: "SA Police", cat: "police" },
      { name: "SA Metropolitan Fire Service (MFS)", cat: "fire" },
      { name: "SA Country Fire Service (CFS)", cat: "fire" },
      { name: "SA State Emergency Service (SASES)", cat: "ses" },
      { name: "SA Ambulance Service (SAAS)", cat: "ambulance" },
    ],
    TAS: [
      { name: "Tasmania Police", cat: "police" },
      { name: "Tasmania Fire Service (TFS)", cat: "fire" },
      { name: "Tasmania State Emergency Service", cat: "ses" },
      { name: "Ambulance Tasmania", cat: "ambulance" },
    ],
    ACT: [
      { name: "ACT Police", cat: "police" },
      { name: "ACT Fire and Rescue", cat: "fire" },
      { name: "ACT Rural Fire Service", cat: "fire" },
      { name: "ACT State Emergency Service", cat: "ses" },
      { name: "ACT Ambulance Service", cat: "ambulance" },
      { name: "Southcare", cat: "ambulance" },
    ],
    NT: [
      { name: "NT Police", cat: "police" },
      { name: "NT Fire and Rescue Service", cat: "fire" },
      { name: "NT State Emergency Service", cat: "ses" },
      { name: "St John Ambulance NT", cat: "ambulance" },
    ],
  };

  // Known vehicle types per department, from data/emergency-vehicles.csv.
  // Agencies without a list fall back to free-text entry in the composer.
  const vehicleTypes = {
    "NSW Ambulance": [
      "Ambulance",
      "Intensive Care Ambulance",
      "Patient Transport Service",
      "Rapid Response",
      "Rescue",
      "Special Operations",
      "Operations Commander",
      "Major Incident Support",
      "Support",
    ],
    "ACT Fire and Rescue": [
      "Heavy Pumper",
      "Heavy Rescue Pumper",
      "Aerial",
      "CAFS Tanker",
      "Tanker",
      "Breathing Apparatus Support",
      "HazMat Response",
      "Pod Truck",
      "Logistics",
      "Support",
      "Commander",
      "Workshops",
      "Community Fire Unit",
    ],
    "Fire and Rescue NSW (FRNSW)": [
      "Tanker Class 1",
      "Pumper Class 2",
      "Pumper Class 3",
      "Aerial Pumper",
      "Turntable Ladder",
      "Aerial Ladder Platform",
      "Heavy HazMat",
      "HazMat Van",
      "HazMat Support",
      "CO2",
      "BA and HazMat",
      "Rehabilitation",
      "Heavy Rescue",
      "Rescue Van",
      "Salvage",
      "Urban Search And Rescue",
      "Pod Truck",
      "Rapid Intervention Vehicle",
      "All Terrain Vehicle",
      "Bulk Water Tanker",
      "Coach",
      "Logistics Support",
      "Scientific Support",
      "Incident Command Vehicle",
      "Support",
      "Prime Mover",
    ],
    "NSW Rural Fire Service (RFS)": [
      "Category 1 Heavy Tanker",
      "Category 2 Medium Tanker",
      "Category 3 Heavy Tanker",
      "Category 4 Medium Tanker",
      "Category 6 Heavy Bushfire Tanker",
      "Category 7 Light Tanker",
      "Category 8 Light Tanker",
      "Category 9 Striker",
      "Category 10 Urban Pumper",
      "Category 11 Urban Pumper",
      "Category 12 Transport",
      "Category 13 Bulk Water Carrier",
      "Category 16 Command Vehicles",
      "Category 17 General Cargo Vehicles",
      "Category 18 Catering Vehicles",
      "Category 19 Communication Vehicles",
      "Category 20 Other Appliances/Vehicles",
    ],
    "Queensland Fire Department": [
      "Pumper Type 1",
      "Pumper Type 2",
      "Pumper Type 3",
      "Pumper Type 4",
      "Pumper Type 4T",
      "Combination Aerial Pumper Appliance",
      "Turntable Ladder",
      "Ladder Platform",
      "Telescopic Aerial Pumper",
      "Emergency Tender",
      "Technical Rescue",
      "Command & Rescue",
      "BA & HazMat Response",
      "Rescue Support",
      "BA Support",
      "Hazmat Support",
      "BA & HazMat Support",
      "Command & Control",
      "Communications",
      "Tanker",
      "Foam",
      "Facilities",
      "Urban Light Attack",
      "Operational Support Unit",
    ],
    "SA Metropolitan Fire Service (MFS)": [
      "Heavy Duty Pumper",
      "Medium Pumper",
      "HazMat/Breathing Apparatus",
      "Rescue",
      "Grassfire Unit",
      "Bulk Water Tanker",
      "Ladder",
      "Skyjet",
      "Combined Aerial Pumping Appliance",
      "Command",
      "Mobile Incident Communications",
      "Hook Truck",
      "Support",
    ],
    "SA Country Fire Service (CFS)": [
      "Quick Response Vehicle",
      "14",
      "22",
      "24",
      "24P",
      "24URP",
      "34",
      "34P",
      "34URP",
      "44",
      "Bulk Water Carrier",
      "Pumper",
      "HazMat",
      "Rescue",
      "Mobile Incident Communications",
      "Logistics",
      "Support",
    ],
    "Tasmania Fire Service (TFS)": [
      "Heavy Pumper",
      "Medium Pumper",
      "Heavy Tanker",
      "Heavy Tanker/Pumper",
      "Heavy Tanker/Pumper/Rescue",
      "Medium Tanker",
      "Light Tanker",
      "Hydraulic Platform",
      "Support",
      "Rescue",
      "CAFS Tanker",
      "HazMat",
      "Command Support",
    ],
    "Fire Rescue Victoria": [
      "Ladder Platform",
      "Teleboom",
      "Aerial Pumper",
      "Pumper Platform",
      "Breathing Apparatus",
      "Breathing Apparatus Support",
      "Mk4 Pumper",
      "Mk5 Pumper",
      "Type 4 Pumper",
      "Heavy Pumper",
      "Series 1 Pumper",
      "Ultra Large Pumper",
      "Mk4 Pumper Tanker",
      "Mk5 Pumper Tanker",
      "Water Tanker",
      "Rescue",
      "HazMat",
      "Transporter",
      "Rehab",
      "Control Unit",
      "District Car",
      "Community Education",
    ],
    "Country Fire Authority": [
      "Ladder Platform",
      "Teleboom",
      "Heavy Pumper",
      "Medium Pumper",
      "Light Pumper",
      "Type 2 Pumper",
      "Type 3 Pumper",
      "Type 3 Light Pumper",
      "Type 3 Small Pumper",
      "Type 3 Medium Pumper",
      "Type 3 Heavy Pumper",
      "Type 4 Pumper",
      "Alpine Pumper",
      "2.2D Pumper Tanker",
      "2.4D Pumper Tanker",
      "Medium Pumper Tanker",
      "Light Tanker",
      "Medium Tanker",
      "Heavy Tanker",
      "Ultra Heavy Tanker",
      "2.4C Medium Tanker",
      "3.4C Heavy Tanker",
      "4.4 Heavy Tanker",
      "4.4R Heavy Tanker",
      "Ultra Light Tanker",
      "1.2.4D Tanker",
      "1.5D Tanker",
      "2.5.2D Tanker",
      "2.2D Tanker",
      "2.4D Tanker",
      "3.2D Tanker",
      "3.4D Tanker",
      "3.4L Tanker",
      "Bulk Water Tanker",
      "Rescue",
      "Slip-On",
      "Salvage",
      "HazMat",
      "Gas Support",
      "Rehab",
      "Big Fill",
      "Hose Layer",
      "Breathing Apparatus Support",
      "Lighting",
      "Pod Truck",
      "Mobile Command Vehicle",
      "Field Command Vehicle",
      "Field Operations Vehicle",
      "Support",
      "Car",
      "Bus",
      "Community Education",
      "District Mechanical Officer",
      "Snow Mobile",
      "Trailer",
    ],
    "Ambulance Victoria": [
      "Paramedic Ambulance",
      "MICA Ambulance",
      "Paramedic Single Response Unit",
      "MICA Single Response Unit",
      "Clinic Transport Services",
      "Community Education",
      "Emergency Support",
      "Protective Equipment",
      "Command & Communications",
      "Helicopter Emergency Medical Service",
    ],
    "Victoria State Emergency Service": [
      "Rescue",
      "Support",
      "Transport",
      "Forward Command Vehicle",
      "Mobile Command Vehicle",
      "Communications",
      "Trailer",
    ],
  };

  // Appliance body builders, same CSV -- suggestions for the cab chassis
  // / body builder field.
  const manufacturers = [
    "Aldom Transport Engineering",
    "Alexander Perrie & Co",
    "Allquip",
    "Australian Fire Company",
    "Bell Environmental",
    "Brimarco",
    "Capital Body Works",
    "CFA Vehicle Manufacturing Plant",
    "Emergency Transport Technology",
    "Fleet Trades",
    "Fraser Fire and Rescue",
    "Frontline Fire and Rescue",
    "Hidrive",
    "International Harvester",
    "KME Fire Apparatus",
    "Kuipers Engineering",
    "Liquip International",
    "Lowes Industries",
    "MacDonald Johnson Engineering",
    "Mader International",
    "MFB Workshops",
    "MFI Service Bodies",
    "Mills-Tui",
    "Mine Corp",
    "Moore Engineering",
    "Multidrive Technology",
    "OKA Australia",
    "Other",
    "Paull and Warner",
    "Pierce Manufacturing",
    "Quik Corp Fire Engineering",
    "Rambler",
    "Rosenbauer",
    "RXI Group",
    "SEM Fire & Rescue (formerly Skilled)",
    "Skilled Equipment Manufacturing",
    "South West Fire",
    "Technifire",
    "TFS Engineering Services",
    "Unknown",
    "Varley Group",
    "WA Fire Appliances",
  ];

  window.FleetVocab = {
    states: Object.keys(departments),
    departments,
    vehicleTypes,
    manufacturers,
    categoryOf(state, agencyName) {
      const list = departments[state] || [];
      const hit = list.find((d) => d.name === agencyName);
      return hit ? hit.cat : null;
    },
    typesFor(agencyName) {
      return vehicleTypes[agencyName] || [];
    },
  };
})();
