-- 004_dashboard.sql  — intentionally a NO-OP (tables split out to the bot DB).
--
-- HISTORY: this migration used to create the dashboard / Discord-bot tables
-- (dash_sessions, dashboard_users, alert_presets, guild_mute_state,
-- channel_mute_state, preset_fire_log, pending_bot_actions) in the MAIN
-- (DATABASE_URL) Postgres, "for free", in case a deployer ran a single shared
-- Postgres for both the archive and the bot.
--
-- Those tables are OWNED by the Discord bot and live in BOT_DATA_DATABASE_URL.
-- They are always created by their real owners, against the bot DB:
--   * discord-bot/apply_schema_presets.py / database.py
--       → alert_presets, guild_mute_state, channel_mute_state,
--         preset_fire_log, pending_bot_actions, dash_sessions, preset_audit_log
--   * backends/node/src/services/dashboardSession.ts  ensureSessionTables()
--       → dash_sessions, dashboard_users   (CREATE IF NOT EXISTS at startup)
-- In a shared-Postgres deploy the bot DB *is* this DB, so those owners still
-- create everything here; on a separate-DB deploy (the normal setup) creating
-- them here only produced empty, never-read duplicate tables in the main DB.
--
-- So the CREATEs were removed to keep the main DB clean. We deliberately do
-- NOT add a DROP here: a migration runs against every deployment, and on a
-- shared-Postgres deploy these are the REAL, populated bot tables — dropping
-- them would destroy live data. Existing empty duplicates on a separate-DB
-- main database should be removed with a one-off manual DROP (safe only when
-- the bot uses its own database).
SELECT 1;
