// Package decoder renders the dump1090 launch script the agent supervises.
//
// The pattern mirrors the pager agent's reader.sh: generate a small shell
// wrapper into the agent's own data dir and supervise `bash <script>`. The
// script's path is unique to this agent, which is what makes it safe for
// KillStale to match on at startup — matching a bare "dump1090" would kill a
// decoder the operator is running for their own purposes.
//
// Everything interpolated into the script is validated here first. The values
// arrive from a server config push, so they are not attacker-controlled in any
// normal sense, but a launcher that pastes remote strings into a shell command
// is exactly the kind of thing that becomes a problem later. Numbers are
// rendered from parsed floats, never from the received text.
package decoder

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

// Params are the decoder settings for one launch.
type Params struct {
	// Bin is the decoder executable (resolved via PATH when bare).
	Bin string
	// JSONDir is where dump1090 writes aircraft.json / stats.json.
	JSONDir string
	// GainDB is the fixed gain in dB, or nil to let the decoder choose. The
	// autogain loop supplies a concrete value here on every restart, so from
	// the decoder's point of view gain is always fixed — the adaptation lives
	// in the agent, not in dump1090.
	GainDB *float64
	// PPM is the crystal correction, or nil for none.
	PPM *int
	// Lat/Lon are the exact antenna position. Without them dump1090 reports no
	// range statistics at all and cannot decode surface positions, which is
	// why the backend makes the map pin mandatory for this node kind.
	Lat *float64
	Lon *float64
}

// MinGain and MaxGain bound what may be written into the launch command.
// 49.6 dB is the top step of the R820T/R820T2 tuner in essentially every RTL
// dongle; librtlsdr clamps anything higher to it anyway.
const (
	MinGain = 0.0
	MaxGain = 49.6
)

// ClampGain constrains g to the tuner's usable range.
func ClampGain(g float64) float64 {
	if g < MinGain {
		return MinGain
	}
	if g > MaxGain {
		return MaxGain
	}
	return g
}

// ParseGain interprets a config gain value. Returns (nil, true) for "auto" or
// empty — meaning "the agent decides" — and (value, true) for a valid fixed
// gain. An unparseable value is rejected rather than silently defaulted: a
// typo'd gain should be visible in the logs, not quietly become max gain.
func ParseGain(raw string) (g *float64, auto bool, ok bool) {
	s := strings.TrimSpace(strings.ToLower(raw))
	if s == "" || s == "auto" {
		return nil, true, true
	}
	f, err := strconv.ParseFloat(s, 64)
	if err != nil {
		return nil, false, false
	}
	c := ClampGain(f)
	return &c, false, true
}

// Args builds the decoder's argument list.
//
// Deliberately no --net: the JSON files are the whole interface, so the
// decoder opens no listening sockets. --quiet keeps its stdout to warnings and
// errors, which the supervisor captures into the component log.
func (p Params) Args() []string {
	args := []string{
		// Device 0: these are dedicated single-dongle receivers. Selecting by
		// index is safe here in a way it would not be on a shared host, where
		// indices reshuffle on replug.
		"--device-index", "0",
		"--quiet",
		"--write-json", p.JSONDir,
		// 1 Hz: matches the file cadence tar1090 expects and is well inside
		// our 5s snapshot interval.
		"--write-json-every", "1",
	}
	if p.GainDB != nil {
		args = append(args, "--gain", strconv.FormatFloat(ClampGain(*p.GainDB), 'f', 1, 64))
	}
	if p.PPM != nil {
		args = append(args, "--ppm", strconv.Itoa(*p.PPM))
	}
	if p.Lat != nil && p.Lon != nil {
		args = append(args,
			"--lat", strconv.FormatFloat(*p.Lat, 'f', 6, 64),
			"--lon", strconv.FormatFloat(*p.Lon, 'f', 6, 64),
			// Publish the exact receiver location in receiver.json. The file
			// never leaves the host — nothing serves it — and the decoder uses
			// it for local surface-position decoding.
			"--json-location-accuracy", "2",
		)
	}
	return args
}

// shQuote wraps a value in single quotes for the generated script, escaping
// any embedded quote. Only the binary path and JSON dir go through this;
// every numeric argument is rendered from a parsed number.
func shQuote(v string) string {
	return "'" + strings.ReplaceAll(v, "'", `'\''`) + "'"
}

// Write renders the launch script to <dir>/dump1090.sh and returns its path.
func Write(dir string, p Params) (string, error) {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", fmt.Errorf("create decoder dir: %w", err)
	}
	bin := strings.TrimSpace(p.Bin)
	if bin == "" {
		bin = "dump1090-fa"
	}

	var b strings.Builder
	b.WriteString("#!/usr/bin/env bash\n")
	b.WriteString("set -euo pipefail\n")
	b.WriteString("# Generated by nodeagent — do not edit; rewritten on every config apply.\n")
	b.WriteString("#\n")
	b.WriteString("# No --net: the agent reads aircraft.json / stats.json from the JSON dir,\n")
	b.WriteString("# so the decoder listens on no ports at all.\n")
	b.WriteString("mkdir -p " + shQuote(p.JSONDir) + "\n")
	// exec so the supervised `bash <script>` process IS the decoder: the
	// supervisor's process-group kill then reaches it directly, and the
	// component's reported state tracks the decoder rather than a wrapper that
	// would outlive it.
	b.WriteString("exec " + shQuote(bin))
	for _, a := range p.Args() {
		b.WriteString(" " + shQuote(a))
	}
	b.WriteString("\n")

	path := filepath.Join(dir, "dump1090.sh")
	if err := os.WriteFile(path, []byte(b.String()), 0o755); err != nil {
		return "", fmt.Errorf("write decoder script: %w", err)
	}
	return path, nil
}
